/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AritcleCard: typeof import('./src/components/AritcleCard.vue')['default']
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    BubbleSort: typeof import('./src/components/algorithm/bubble-sort.vue')['default']
    LeftSection: typeof import('./src/components/algorithm/LeftSection.vue')['default']
    QuickSort: typeof import('./src/components/algorithm/quick-sort.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortingVisualizer: typeof import('./src/components/SortingVisualizer.vue')['default']
    VisualizationContainer: typeof import('./src/components/algorithm/VisualizationContainer.vue')['default']
  }
}
