/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminModal: typeof import('./src/components/admin/AdminModal.vue')['default']
    ArticleCard: typeof import('./src/components/article/ArticleCard.vue')['default']
    ArticleComments: typeof import('./src/components/article/ArticleComments.vue')['default']
    ArticleFilter: typeof import('./src/components/article/ArticleFilter.vue')['default']
    ArticleTableRow: typeof import('./src/components/article/ArticleTableRow.vue')['default']
    ArticleTitle: typeof import('./src/components/article/ArticleTitle.vue')['default']
    ArticleToc: typeof import('./src/components/article/ArticleToc.vue')['default']
    BaseControlPanel: typeof import('./src/components/composable/BaseControlPanel.vue')['default']
    BaseEditor: typeof import('./src/components/composable/BaseEditor.vue')['default']
    BaseMetricCard: typeof import('./src/components/composable/BaseMetricCard.vue')['default']
    BaseModal: typeof import('./src/components/composable/BaseModal.vue')['default']
    BatchOperations: typeof import('./src/components/common/BatchOperations.vue')['default']
    BatchOperationToolbar: typeof import('./src/components/common/BatchOperationToolbar.vue')['default']
    CommentInput: typeof import('./src/components/article/CommentInput.vue')['default']
    ConfirmDialog: typeof import('./src/components/common/ConfirmDialog.vue')['default']
    DPCanvas: typeof import('./src/components/dp/DPCanvas.vue')['default']
    DPControlPanel: typeof import('./src/components/dp/DPControlPanel.vue')['default']
    DPStatus: typeof import('./src/components/dp/DPStatus.vue')['default']
    GalleryItem: typeof import('./src/components/GalleryItem.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    MusicPlayer_Enhanced: typeof import('./src/components/MusicPlayer_Enhanced.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OJFilterPanel: typeof import('./src/components/oj/OJFilterPanel.vue')['default']
    OJLanguageSelector: typeof import('./src/components/oj/OJLanguageSelector.vue')['default']
    OJPagination: typeof import('./src/components/oj/OJPagination.vue')['default']
    OJProblemCard: typeof import('./src/components/oj/OJProblemCard.vue')['default']
    OJProblemDetail: typeof import('./src/components/oj/OJProblemDetail.vue')['default']
    OJResultPanel: typeof import('./src/components/oj/OJResultPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCanvas: typeof import('./src/components/search/SearchCanvas.vue')['default']
    SearchControlPanel: typeof import('./src/components/search/SearchControlPanel.vue')['default']
    SearchStatus: typeof import('./src/components/search/SearchStatus.vue')['default']
    SortCanvas: typeof import('./src/components/sort/SortCanvas.vue')['default']
    SortControlPanel: typeof import('./src/components/sort/SortControlPanel.vue')['default']
    SortStatus: typeof import('./src/components/sort/SortStatus.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    VirtualList: typeof import('./src/components/common/VirtualList.vue')['default']
  }
}
